print("Hello from lesson 1")
print("i like beans")
print("my name is justin")
print("i am 12 grade wise cuz i p6 but 11 age wise as my BD not pass yet")
print("i am in infoccom")
print("i would buy myself some robux then give some to my parents so they dont say im selfish then use the rest for beans and potatos")
######### The below is the code required for task 2a ##########
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
print("7")
# print("8")
# print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
# print("October")
# print("November")
print("December")
print("2014")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
# print("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
# print("2030")

############## Below is the code for task 2b ##############
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
# print("7")
# print("8")
# print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
# print("October")
# print("November")
# print("December")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
# print("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
#print("2030")





print("hello world")
print("my favourite food is beans")
print("my birthday is on december 7 2014")

print("wake up")
print("go toilet")
print("drink water")
print("eat 1/64 of the bread my dad gave me")
print("brush teeth")
print("change")
print("go school")


print("wake up and get out of bed.")
print("pour milk and cereal into a bowl")
print("eat your breakfast")